name: Makefile CI

on:
  push:
    branches: [ "mob" ]
  pull_request:
    branches: [ "mob" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run Test
      run: make test

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: code
        path: /tinycc-mob
